### ISSUE TITLE
1.7版本有BUG， 界面初始化后， 第一个tab的图标应该是选中状态

### ISSUE THREAD

**Issue by superyfwy** [panpf/pager-indicator#5]

**Comment by xiaopansky** [comment]
多谢你的反馈，我看了一下目前表现出来的问题是如果是tab在布局中写的那么应该选中的tab却没有选中状态。临时的解决方案是你可以换成在代码中通过TabViewFactory来添加tab或者调一下viewPager.setCurrentItem(1)再调一下viewPager.setCurrentItem(0)，触发一下OnPageChangedListener。我会尽快解决这个问题，再次感谢你的反馈！

**Comment by xiaopansky** [comment]
已经升级到1.7.1了，修复了这个BUG，感谢你的反馈！
